---
blackbox_exporter_version: "latest"
blackbox_exporter_binary_url:
  "https://github.com/{{ _blackbox_exporter_repo }}/releases/download/v{{ blackbox_exporter_version }}/\
  blackbox_exporter-{{ blackbox_exporter_version }}.linux-{{ go_arch_map[ansible_architecture] |
  default(ansible_architecture) }}.tar.gz"
blackbox_exporter_skip_install: false

blackbox_exporter_web_port: 9115
blackbox_exporter_web_listen_address: "127.0.0.1:{{ blackbox_exporter_web_port }}"
blackbox_exporter_web_external_url: "/prometheus"

blackbox_exporter_group: "prometheus"
blackbox_exporter_user: "blackbox-exporter"

blackbox_exporter_cli_flags: {}
# blackbox_exporter_cli_flags:
#   log.level: "warn"

blackbox_exporter_configuration_modules:
  http:
    prober: http
    timeout: 5s
    http:
      preferred_ip_protocol: "ip4"
      ip_protocol_fallback: false
      valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
      method: GET
      valid_status_codes: []
      fail_if_ssl: false
      fail_if_not_ssl: false
      follow_redirects: true
      tls_config:
        insecure_skip_verify: true
  icmp:
    prober: icmp
    timeout: 1s
    icmp:
      preferred_ip_protocol: ip4
  ssh:
    prober: tcp
    timeout: 5s
    tcp:
      query_response:
        - expect: "^SSH-2.0-"
#  tcp_connect:
#    prober: tcp
#    timeout: 5s
#  dns_test:
#    prober: dns
#    timeout: 5s
#    dns:
#      preferred_ip_protocol: ip6
#      validate_answer_rrs:
#        fail_if_matches_regexp: [test]

# Where to put the blackbox_exporter.yml main configuration file
blackbox_exporter_config_dir: /etc
