---
- name: Create systemd service unit
  ansible.builtin.template:
    src: blackbox_exporter.service.j2
    dest: /etc/systemd/system/blackbox_exporter.service
    owner: "{{ blackbox_exporter_user }}"
    group: "{{ blackbox_exporter_group }}"
    mode: "0640"
  notify:
    - restart blackbox_exporter

- name: Configure blackbox exporter
  ansible.builtin.template:
    src: blackbox_exporter.yml.j2
    dest: "{{ blackbox_exporter_config_dir }}/blackbox_exporter.yml"
    owner: "{{ blackbox_exporter_user }}"
    group: "{{ blackbox_exporter_group }}"
    mode: "0644"
  notify:
    - reload blackbox_exporter
