---
- name: Assert usage of systemd as an init system
  ansible.builtin.assert:
    that: ansible_service_mgr == 'systemd'
    msg: "This role only works with systemd"

- name: Install package fact dependencies
  become: true
  ansible.builtin.package:
    name: "{{ _pkg_fact_req }}"
    state: present
  register: _progress_status
  until: _progress_status is succeeded
  delay: 5
  retries: 5
  when: (_pkg_fact_req)
  vars:
    _pkg_fact_req: "{% if (ansible_pkg_mgr == 'apt') %}\
      {{ ('python-apt' if ansible_python_version is version('3', '<') else 'python3-apt') }}
      {% else %}\
      {% endif %}"

- name: Gather package facts
  ansible.builtin.package_facts:
  when: "not 'packages' in ansible_facts"

- name: Common preflight
  ansible.builtin.include_role:
    name: prometheus.prometheus._common
    tasks_from: preflight.yml
  vars:
    _common_dependencies: "{{ _blackbox_exporter_dependencies }}"
    _common_web_listen_address: "{{ blackbox_exporter_web_listen_address }}"

- name: Assert that used version supports listen address type
  ansible.builtin.assert:
    that:
      - >-
        blackbox_exporter_web_listen_address is string
        or
        (
          blackbox_exporter_version is version('0.23.0', '>=') and
          blackbox_exporter_web_listen_address | type_debug == "list"
        )

- name: Discover latest version
  ansible.builtin.set_fact:
    blackbox_exporter_version:
      "{{ (lookup('url', 'https://api.github.com/repos/{{ _blackbox_exporter_repo }}/releases/latest', headers=_github_api_headers,
      split_lines=False) | from_json).get('tag_name') | replace('v', '') }}"
  run_once: true
  until: blackbox_exporter_version is version('0.0.0', '>=')
  retries: 10
  when:
    - blackbox_exporter_version == "latest"
  tags:
    - blackbox_exporter
    - install
    - blackbox_exporter_install
    - download
    - blackbox_exporter_download
