---
- name: Copy the SNMP Exporter systemd service file
  ansible.builtin.template:
    src: snmp_exporter.service.j2
    dest: /etc/systemd/system/snmp_exporter.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - restart snmp_exporter

- name: Download snmp configuration file from github repository
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/prometheus/snmp_exporter/v{{ snmp_exporter_version }}/snmp.yml"
    dest: /etc/snmp_exporter/snmp.yml
    validate_certs: false
    owner: "{{ snmp_exporter_system_user }}"
    group: "{{ snmp_exporter_system_group }}"
    mode: "0640"
  register: _download_config
  until: _download_config is success
  retries: 5
  delay: 2
  notify:
    - restart snmp_exporter
  when: not (snmp_exporter_config_file)

- name: Copy configuration file
  ansible.builtin.template:
    src: "{{ snmp_exporter_config_file }}"
    dest: /etc/snmp_exporter/snmp.yml
    owner: "{{ snmp_exporter_system_user }}"
    group: "{{ snmp_exporter_system_group }}"
    mode: "0640"
  no_log: "{{ false if (lookup('env', 'CI')) or (lookup('env', 'MOLECULE_PROVISIONER_NAME')) else true }}"
  notify:
    - restart snmp_exporter
  when: (snmp_exporter_config_file)
