---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  ansible-lint .
platforms:
  - name: molecule-instance
    image: geerlingguy/docker-${MOLECULE_DISTRO:-debian12}-ansible:latest
    command: ${MOLECULE_DOCKER_COMMAND:-/sbin/init}
    pre_build_image: true
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
provisioner:
  inventory:
    group_vars:
      all:
        systemd_exporter_web_listen_address: "127.0.0.1:9558"
