name: CI
on:
  workflow_dispatch:
    inputs:
      runKics:
        description: Run KICS scan
        type: boolean
        default: true
      runLint:
        description: Run Ansible Lint
        type: boolean
        default: true
      runMolecule:
        description: Run Ansible Molecule
        type: boolean
        default: true
      publishRelease:
        description: Publish Release
        type: boolean
        default: false
        required: false
  push:
    paths-ignore: ["**.md", "LICENSE", ".github/dependabot.yml"]
    branches: ["master", "main"]
  pull_request:
    branches: ["master", "main"]

env:
  ROLES_PATH: "roles/"

jobs:
  init:
    name: Initialize CI for ${{ github.ref_name }}
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get roles list in json
        id: roles-list
        run: echo "roles-list=$(ls ${{ env.ROLES_PATH }} | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
        shell: bash

    outputs:
      roles-list: ${{ steps.roles-list.outputs.roles-list }}

  scan:
    name: Checkmarx KICS
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [init]
    if: |
      inputs.runKics == true || 
      github.event_name == 'push' || 
      github.event_name == 'pull_request' || 
      github.event_name == 'schedule'
    permissions:
      contents: read
      issues: write
      pull-requests: write
      security-events: write
      actions: read
    strategy:
      matrix:
        roles: ${{ fromJson(needs.init.outputs.roles-list) }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          disable-sudo: true
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Run KICS scan
        uses: checkmarx/kics-github-action@8a44970e3d2eca668be41abe9d4e06709c3b3609 # v1.7.0
        with:
          path: "roles/${{ matrix.roles }}"
          fail_on: high
          output_formats: "json,sarif"
          exclude_paths: ".github/workflows/scorecard.yml"
        continue-on-error: true

      - name: Upload to code-scanning
        uses: github/codeql-action/upload-sarif@c7f9125735019aa87cfc361530512d50ea439c71 # v3.25.1
        with:
          sarif_file: results.sarif

  lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [init]
    if: |
      inputs.runLint == true ||
      github.event_name == 'push' ||
      github.event_name == 'pull_request' ||
      github.event_name == 'schedule'
    strategy:
      matrix:
        roles: ${{ fromJson(needs.init.outputs.roles-list) }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          disable-sudo: true
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Run Ansible Lint
        uses: unleftie/ansible-lint-action@f6c9ea06aebdd94a4a7e0414d630fdb6832b1083 # v1.1.0
        with:
          path: "roles/${{ matrix.roles }}"

  molecule:
    name: Ansible Molecule
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: [init]
    if: |
      inputs.runMolecule == true ||
      github.event_name == 'push' ||
      github.event_name == 'pull_request' ||
      github.event_name == 'schedule'
    strategy:
      fail-fast: false
      matrix:
        roles: ${{ fromJson(needs.init.outputs.roles-list) }}
        distro:
          - debian12

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          disable-sudo: true
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Run Ansible Molecule
        uses: unleftie/ansible-molecule-action@e8cecf7f6dfab2293dd28df032318e6a698c60a3 # v1.7.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          role_name: ${{ matrix.roles }}
          distro: ${{ matrix.distro }}
          working_directory: "roles/${{ matrix.roles }}"

  release:
    name: Publish Release
    runs-on: ubuntu-latest
    if: inputs.publishRelease == true || github.event_name == 'push'
    needs: [scan, lint, molecule]
    permissions:
      packages: write
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@cb425203a562475bca039ba4dbf90c7f9ac790f4 #v4.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          extra_plugins: conventional-changelog-conventionalcommits@6.1.0
